Fixed some shortcut conditions in git module

diff --git a/dottle b/dottle
--- a/dottle
+++ b/dottle
@@ -189,19 +189,6 @@ get_git () {
     fi
     output debug "VERIFY_SSL: '${VERIFY_SSL}'"
 
-    # force flag is set
-    if [ "$(get_flag "$FLAGS" 'force')" = 'true' ]; then
-        if ! command -v git > /dev/null; then
-            output error "git is not installed"
-            return 1
-        fi
-        output debug "force flag is set to true. I will do my best to fulfil your wishes master"
-        [ "$(get_flag "$FLAGS" 'backup')" = 'true' ] && backup "$DEST"
-        rm -rf "$DEST"
-        mkdir -p "$DEST"
-        git --config "http.sslVerify=$VERIFY_SSL" clone "$RECURSIVE" --branch "$BRANCH" "$REPO" "$DEST" || \
-            (output error "Couldn't clone '$REPO' into '$DEST'"; return 1)
-    fi
     # if git is not installed fail
     if ! command -v git > /dev/null && [ "$(get_flag "$FLAGS" 'tar_magic')" = 'false' ]; then
         output error "git is not installed and tar_magic flag is not set"
@@ -212,24 +199,35 @@ get_git () {
             [ "$(get_flag "$FLAGS" 'update')" = 'true' ] && \
             (cd "$DEST"; [ "$(git config --get "remote.${REMOTE}.url")" = "${REPO}" ]); then
         (
-        cd "$DEST" || \
-            (output error "Couldn't \`cd\` into '$DEST'"; return 1)
+        if ! cd "$DEST"; then
+            output error "Couldn't \`cd\` into '$DEST'"
+            return 1
+        fi
 
-        git config http.sslVerify "$VERIFY_SSL" || \
-            (output error "Couldn't set config"; return 1)
+        if ! git config http.sslVerify "$VERIFY_SSL"; then
+            output error "Couldn't set config"
+            return 1
+        fi
 
         output debug "git 'checkout' '$BRANCH'"
-        git checkout "$BRANCH" || \
-            (output error "Couldn't checkout '$BRANCH'"; return 1)
+        if ! git checkout "$BRANCH" > /dev/null 2>&1; then
+            output error "Couldn't checkout '$BRANCH'"
+            return 1
+        fi
 
+        output running "pulling '$BRANCH' branch from '$REPO'\n"
         output debug "git 'pull' '$REMOTE' '$BRANCH'"
-        git pull "$REMOTE" "$BRANCH" || \
-            (output error "Couldn't pull '$BRANCH' branch from '$REMOTE'"; return 1)
+        if ! git pull "$REMOTE" "$BRANCH"; then
+            output error "Couldn't pull '$BRANCH' branch from '$REMOTE'"
+            return 1
+        fi
 
         if [ "$(get_flag "$FLAGS" 'recursive')" = 'true' ]; then
             output debug "git submodule update --init --recursive"
-            git submodule update --init --recursive || \
-                (output error "Couldn't update submodules"; return 1)
+            if ! git submodule update --init --recursive; then
+                output error "Couldn't update submodules"
+                return 1
+            fi
         fi
         ) && output ok "Pulled successfully"
     else
@@ -238,8 +236,10 @@ get_git () {
         mkdir -p "$DEST"
         if command -v git > /dev/null; then
             output debug "git clone --config 'http.sslVerify=$VERIFY_SSL' '$RECURSIVE' --branch '$BRANCH' '$REPO' '$DEST'"
-            git clone --config "http.sslVerify=$VERIFY_SSL" "$RECURSIVE" --branch "$BRANCH" "$REPO" "$DEST" || \
-                (output error "git clone command failed"; return 1)
+            if ! git clone --config "http.sslVerify=$VERIFY_SSL" "$RECURSIVE" --branch "$BRANCH" "$REPO" "$DEST"; then
+                output error "git clone command failed"
+                return 1
+            fi
         else
             output error "tar_magic is not implemented yet"
         fi
